### ISSUE TITLE
Custom RegisterForm

### ISSUE THREAD

**Issue by AMilkov** [nkostadinov/yii2-user#1]
What is the recommended approach to implement custom registration form and view?  
For example if we need some additional attributes, say DOB or country of birth.

**Comment by nkostadinov** [comment]
Hi @AMilkov ,

If you are using the user module(not just the component) the view can be easily overridden through "registerView" property of the module. The view has $model variable passed to it. The $model var is instance of Yii::$app->user->registerForm(property of the component) which defaults to 'nkostadinov\user\models\forms\SignupForm'. You can specify different registerForm class by extending 'nkostadinov\user\models\forms\SignupForm' and adding you new fields there.

Example config:

```
    'components' => [
        'user' => [
            'class' => 'nkostadinov\user\components\User',
            'registerForm' => 'nkostadinov\user\models\forms\SignupForm', //here you can change the signup form which holds the registration validation logic and fields
        ],
......
    'modules' => [
        'user' => [
             'class' => 'nkostadinov\user\Module',
             'registerView' => '@nkostadinov/user/views/registration/signup', //here you setup the view file used in the registration process(using $model instance of registerForm)
        ],
    ],
```

In the SignupForm the "signup" method is responsible for creating a new instance of "identityClass" (AR of the user) and passing this to the register method of the user component which does the actual registration, persisting the user in the DB, sending confirmation mail and etc.

**Comment by AMilkov** [comment]
Thank you @nkostadinov !

What are your recommendations for the best way to include the oAuth providers (FB, LinkedIn, Google) in the Signup process?

**Comment by nkostadinov** [comment]
The oAuth providers are used like it is specified in the [Yii2 documentation](http://www.yiiframework.com/doc-2.0/yii-authclient-collection.html). You specify the providers in the authClientCollection in the config. And the in the view you need to render the options like this:

```
        <?php if (Yii::$app->get("authClientCollection", false)): ?>
            <div>
                <?= AuthChoice::widget([
                    'baseAuthUrl' => [ '/'.$this->context->module->id . '/security/auth'], //the module id is the name of the user module - probably 'user'
                    'popupMode' => false,
                ]) ?>
            </div>
        <?php endif; ?>
```
