### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by Ariestattoo** [nkostadinov/yii2-user#11]
Can we add username to the rules for the User model when safeAttributes is in play, otherwise the username is not modifiable. 
As well, simply from the point of someone learning. 

Why
`if (($model = Yii::$app->user->listUsers()->andWhere(['id' => $id])->one()) !== null) {
            return $model;`

instead of 
`if(($model = Yii::$app->user->identity->findIdentity($id)))
        { return $model;`

Thanks for all the great work guys

**Comment by nkostadinov** [comment]
You are right about that. The username should be added to the safe attributes when the configuration requires username(Yii::$app->user->requireUsername === true). I fixed it by adding logic to the rules method of the identity class.

For the second part :
`$model = Yii::$app->user->listUsers()->andWhere(['id' => $id])->one()`

The idea behind this is that listUsers() returns a UserQuery object which is in fact the search class for the users. You can set you own implementation via identityClass::find method override or DI or listUsers override. So you can add your custom logic to the listUsers method. Everywhere where the module queries the users we use this method so you can override and customize it from one central place.

**Comment by Ariestattoo** [comment]
Nice! Thanks for the explanation.
